BASE_PATH:
SITE_PATH: http://vagabondize.github.io
qiniu: http://zhuowenli.qiniudn.com

paginate: 30 # pagination based on number of posts
paginate_path: "page:num" #pagination generated sub path format
encoding: utf-8
permalink: /:categories/:title.html

markdown: kramdown

# highlighter: rouge
highlighter: pygments

name: 李俊秋
title: 李俊秋

author:
  name: 李俊秋
  email: akikun829@163.com
  github: vagabondize
  twitter: vagabondize
  bio: 所有未在美中度过的生活，都是被浪费了。

rss_path: rss.xml

include:      [".htaccess"]
exclude:      ["*.codekit", "*.lock", "Gulpfile.js", "Gemfile", "LICENSE", "node_modules"]
keep_files:   [".git"]